#############################################################################
# Makefile for building: libcantamus.so.1.0.0
# Generated by qmake (3.1) (Qt 5.13.2)
# Project:  libcantamus.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile libcantamus.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = x86_64-pc-linux-gnu-gcc
CXX           = x86_64-pc-linux-gnu-g++
DEFINES       = -DLIBCANTAMUS
CFLAGS        = -pipe -mtune=generic -march=x86-64 -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -g -fPIC -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -fPIC -std=c++11 -fpermissive -mtune=generic -march=x86-64 -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -g -fPIC -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cantamus1.0.0
DISTDIR = /home/cincin/libcantamus/.tmp/cantamus1.0.0
LINK          = x86_64-pc-linux-gnu-g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common -Wl,-O1 -Wl,-z,relro -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common -Wl,-O1 -Wl,-z,relro -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common -shared -Wl,-soname,libcantamus.so.1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = handleust.cpp 
OBJECTS       = handleust.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt5/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCalendarCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Marble.pri \
		/usr/lib/qt5/mkspecs/modules/qt_MediaWiki.pri \
		/usr/lib/qt5/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		libcantamus.pro handleust.h handleust.cpp
QMAKE_TARGET  = cantamus
DESTDIR       = 
TARGET        = libcantamus.so.1.0.0
TARGETA       = libcantamus.a
TARGET0       = libcantamus.so
TARGETD       = libcantamus.so.1.0.0
TARGET1       = libcantamus.so.1
TARGET2       = libcantamus.so.1.0


first: all
####### Build rules

libcantamus.so.1.0.0:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: libcantamus.a

libcantamus.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: libcantamus.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt5/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCalendarCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Marble.pri \
		/usr/lib/qt5/mkspecs/modules/qt_MediaWiki.pri \
		/usr/lib/qt5/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		libcantamus.pro
	$(QMAKE) -o Makefile libcantamus.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/qt5/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/qt5/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt5/mkspecs/modules/qt_ContactEditor.pri:
/usr/lib/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt5/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt5/mkspecs/modules/qt_KCalendarCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt5/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt5/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/qt5/mkspecs/modules/qt_KMime.pri:
/usr/lib/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt5/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt5/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt5/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt5/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_Marble.pri:
/usr/lib/qt5/mkspecs/modules/qt_MediaWiki.pri:
/usr/lib/qt5/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib/qt5/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt5/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt5/mkspecs/modules/qt_Qt5Keychain.pri:
/usr/lib/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
libcantamus.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile libcantamus.pro

qmake_all: FORCE


all: Makefile libcantamus.so.1.0.0

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

handleust.o: handleust.cpp handleust.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handleust.o handleust.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(QINSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

